# Generated by Django 2.0.6 on 2018-06-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('nit', models.CharField(max_length=12, verbose_name='NIT')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Número telefónico')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('contact_person_name', models.CharField(max_length=255, verbose_name='Nombre persona de contacto')),
                ('contact_person_email', models.EmailField(max_length=255, verbose_name='Email persona de contacto')),
                ('contact_person_charge', models.CharField(max_length=255, verbose_name='Cargo persona de contacto')),
                ('contact_person_phone', models.CharField(max_length=10, verbose_name='Número telefónico persona de contacto')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name='Sitio Web')),
            ],
            options={
                'verbose_name': 'Companía',
                'verbose_name_plural': 'Compañías',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_validated',
        ),
    ]
