# Generated by Django 2.0.6 on 2018-07-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_person_charge',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo persona de contacto'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_person_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email persona de contacto'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_person_phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número telefónico persona de contacto'),
        ),
        migrations.AlterField(
            model_name='company',
            name='nit',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número telefónico'),
        ),
    ]
