# Generated by Django 2.0.6 on 2018-06-21 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usertoken'),
        ('gathering', '0002_auto_20180620_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_company_forms', to='users.Company', verbose_name='Compañia'),
        ),
    ]
